/*
DQL
   WHERE
      COMPARISION OPERATORS
         =,<=,>=,<,>,!= or <>
      ARITHEMETIC OPERATORS
	     +,-,*,/,%
      LOGICAL OPERATORS
         and,or
      MEMBERSHIP OPERATORS
         in,not in,between

	DISTINCT
	LIMIT
*/
/*
SQL LANGUAGE COMMANDS
  DDL -- DATA DEFINITION LANGUAGE
		 CREATE,ALTER,DROP,TRUNCATE
  DML -- DATA MANUPLATION LANGUAGE
         INSERT,UPDATE,DELETE
  DQL -- DATA QUERY LANGUAGE
         SELECT
  TCL -- TRANSACTION CONTROL LANGUAGE
         COMMIT,ROLLBACK
*/
#                                                    DATA QUERY LANGUAGE

/*
DATABASE -- is a collection of tables
TABLE -- is a collection of rows and columns
*/

--  SYNTAX : TO SELECT DATABASE WHICH WE WANT TO USE -- USE<DATABASEname>;
USE MAVENMOVIES;

--  SYNTAX : SELECT <COLUMNS> FROM <TABLE>;
SELECT * FROM CUSTOMER; -- ALL COLUMNS
SELECT FIRST_NAME,LAST_NAME,EMAIL FROM CUSTOMER;
SELECT FIRST_NAME FROM CUSTOMER;
SELECT
    Customer_id,
    first_name,
    last_name,
    Email
FROM
    Customer;
-- ; is a DELIMITER
SELECT
	Customer_id,
	Amount,
	Payment_id
FROM 
    Payment;
/*
DATATYPES --
*/
 
 -- ARITHEMETIC OPERATORS
SELECT 2+3;
SELECT 2*3;
SELECT 4/2;
SELECT 4%2;
-- COMPARISION OPERATORS
SELECT 4=2;
SELECT 4=4;
SELECT 4=2*2;
SELECT 4!=3*2;
SELECT Customer_id,first_name,last_name,Email FROM Customer
WHERE Customer_id=3;
SELECT * FROM payment
where customer_id=599;
SELECT * FROM payment
where customer_id=3;
SELECT * FROM payment
where customer_id!=3;
SELECT * FROM payment
where customer_id<>3;
SELECT * FROM payment
where customer_id<3;
SELECT * FROM payment
where customer_id>3;
SELECT * FROM payment
where customer_id<=3;
SELECT * FROM payment
where customer_id>=3;
SELECT Customer_id, first_name, last_name, Email FROM Customer
where first_name= 'seth'; -- '  ' is used for string data or date datatypes
SELECT Customer_id, first_name, last_name, Email FROM Customer
where first_name >'seth'; -- it works in the manner of dictionary
SELECT * FROM PAYMENT
WHERE PAYMENT_DATE = '2005-05-25 11:30:37'; -- YYYY-MM-DD HH:MM:SS
SELECT * FROM PAYMENT
WHERE PAYMENT_DATE = '2005-05-25';
SELECT * FROM PAYMENT
WHERE PAYMENT_DATE > '2005-05-25';
SELECT * FROM PAYMENT
WHERE PAYMENT_DATE < '2005-05-25';
SELECT * FROM PAYMENT
WHERE PAYMENT_DATE <= '2005-05-25 11:30:37';
SELECT * FROM PAYMENT
WHERE PAYMENT_DATE >= '2005-05-25 11:30:37';

--  RANGE OPERATORS/MEMBERSHIP OPERATORS
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID BETWEEN 150 AND 200 ; -- FIRST VALUE HAS TO BE SMALLER AND NEXT TO BE BIGGER
SELECT * FROM CUSTOMER
WHERE FIRST_NAME BETWEEN 'S' AND 'U' ; -- GIVES ALL THE NAMES STARTING WITH S,T,U 
-- CAN WE SELECT EVEN/ODD NUMBERS ONLY IN 'BETWEEN'OPERATOR
--  FOR A LIST OF ITEMS WHICH ARE RANDOM
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID IN(1,15,25,485,599); -- IN operator works like equal to but with multiple values
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID NOT IN(1,15,25,485,599); -- GIVES ALL THE OTHER VALUES EXCEPT THESE VALUES IN ()
SELECT * FROM CUSTOMER
WHERE FIRST_NAME IN('SETH','PATRICIA','KAREN');
-- LOGICAL OPERATORS
-- AND/OR
# GET ME THE DATA FROM CUSTOMER TABLE WHOSE FIRST_NAME IS SARA AND CUSTOMER_ID IS NOT EQUAL TO 4
# AND OPERATOR CHECKS FOR ALL THE CONDITIONS TO BE SATISFIED
SELECT * FROM CUSTOMER
WHERE FIRST_NAME = 'SARA' AND CUSTOMER_ID<>4;
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID BETWEEN 50 and 150 AND FIRST_NAME BETWEEN 'S' and 'T';
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID BETWEEN 50 and 150 AND FIRST_NAME BETWEEN 'S' and 'TZZZZZZ';
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID NOT BETWEEN 50 and 150 AND FIRST_NAME BETWEEN 'S' and 'TZZZZZZZZ';
SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID NOT BETWEEN 50 and 150 AND FIRST_NAME BETWEEN 'S' and 'U';
-- OR 
SELECT * FROM CUSTOMER 
WHERE FIRST_NAME>'T' OR CUSTOMER_ID BETWEEN 1 AND 50;

# GET ALL THE DETAILS OF CUSTOMERS WHOSE NAMES EITHER START WITH S OR WHOSE NAMES STARTS WITH W
SELECT * FROM CUSTOMER 
WHERE FIRST_NAME  BETWEEN 'S' AND 'T' OR FIRST_NAME  BETWEEN 'W' AND 'X';
SELECT * FROM CUSTOMER 
WHERE
(FIRST_NAME >='S' AND FIRST_NAME<'T')
or
(FIRST_NAME >='W' AND FIRST_NAME<'X')
/* GET THE DETAILS OF THE CUSTOMER WHOSE CUSTOMER ID IS IN BETWEEEN 15 TO 135 AND WHOSE FIRST_NAME STARTS WITH EITHER A,B,J,M
 OR WHOSE LAST_NAME STARTS WITH K,L,W  AND CUSTOMER_ID BETWEEN 300 TO 445
*/
SELECT * FROM CUSTOMER 
WHERE
((CUSTOMER_ID BETWEEN 15 AND 135) AND(FIRST_NAME >='A'AND FIRST_NAME<'C' OR FIRST_NAME >='J'AND FIRST_NAME<'N'))
OR
((CUSTOMER_ID BETWEEN 300 AND 445) AND (FIRST_NAME >='K'AND FIRST_NAME<'M' AND FIRST_NAME >='W'AND FIRST_NAME<'X'));


SELECT * FROM CUSTOMER 
WHERE
((CUSTOMER_ID BETWEEN 15 AND 35)AND(FIRST_NAME BETWEEN 'A' AND 'B' OR FIRST_NAME BETWEEN 'B' AND 'C' OR FIRST_NAME BETWEEN 'J' AND 'K' OR FIRST_NAME BETWEEN 'M' AND 'N'))
OR
((CUSTOMER_ID BETWEEN 300 AND 445)AND(LAST_NAME BETWEEN 'K' AND 'L' OR LAST_NAME BETWEEN 'L' AND 'M' OR LAST_NAME BETWEEN 'W' AND 'X'));

SELECT * FROM CUSTOMER 
WHERE
((CUSTOMER_ID BETWEEN 15 AND 35)AND(FIRST_NAME BETWEEN 'A' AND 'C' OR FIRST_NAME BETWEEN 'J' AND 'K' OR FIRST_NAME BETWEEN 'M' AND 'N'))
OR
((CUSTOMER_ID BETWEEN 300 AND 445)AND(LAST_NAME BETWEEN 'K' AND 'M' OR LAST_NAME BETWEEN 'W' AND 'X'));