SELECT ROUND(2.456);
SELECT ROUND(2.456,1);
SELECT ROUND(2.456,2);
SELECT TRUNCATE(2.456);
SELECT TRUNCATE(2.456,1);
SELECT TRUNCATE(2.456,2);

SELECT * FROM PAYMENT;
-- GET THE DIFFERENCE BETWEEN TODAYS DATE AND EVERY PAYMENT_DATE
SELECT DATEDIFF(PAYMENT_DATE,SYSDATE()) FROM PAYMENT ; -- GIVES IN DAYS
SELECT DATEDIFF(PAYMENT_DATE,SYSDATE())/7 FROM PAYMENT ; -- GIVES IN WEEKS
SELECT DATEDIFF(PAYMENT_DATE,SYSDATE())/30 FROM PAYMENT ; -- GIVES IN MONTHS
SELECT DATEDIFF(PAYMENT_DATE,SYSDATE())/30/12 FROM PAYMENT ; -- GIVES IN YEARS

SELECT REVERSE(FIRST_NAME) FROM CUSTOMER;
SELECT replace('ROHIT AND KOHLI COMBINATION IS GREAT','GREAT','EPIC');
SELECT REPLACE (DESCRIPTION,'A','@') FROM FILM;
select replace(email,'@','$') from customer;
select * from customer limit 594,5;

/*
PRIMARY KEY
FOREIGN KEY
   
|      CUSTOMER     |         |          ADDRESS       |
| CID |NAME         |         |  AID | CITY       |CID |
| 1   | DV          |         |   1  | HYD        | 1  |
| 2   | SANTOSH     |         |   2  | BENG       | 1  |
| 4   | KUSUMALATHA |         |   3  | NOIDA      | 2  |
| 5   | BIGYAN      |         |   4  | DELHI      | 2  |
  PRIM						  |   5  | KOLKATA    | 4  |
  KEY						  |   6  | MUMBAI     | 4  |
							  |   8  | COIMBATORE | 9  | -- THIS IS A ORPHAN RECORD WHICH IS VERY DAGEROUS FOR THE DATA TO COUNTER SUCH RECORDS YOU SHOULD
								PRIM						ESTABLISH A RULE THAT CHECKS THE REFERENTIAL INTYEGRITY .
								KEY					    	TO ENABLE REFERENTIAL INTEGRITY WE USE FOREIGN KEY .
															THIS ENABLES REFERENTIAL INTEGRITY.
                               
                               
 -- PRIMARY KEY:                              
CID COLUMN IN CUSTOMER TABLE AND ADRESS ID IN ADRESS TABLE ARE PRIMARY KEYS BECAUSE THEY ACT AS A UNIQUE INDENTIFIER C0LUMN.
PRIMARY KEY IS A COLUMN THAT UNIQUELY IDENTIFIES THE DATA.
EVERY TABLE HAS A PRIMARY KEY IN MOST OF THE CASES
THERE WILL BE ONLY ONE PRIMARY KEY IN A TABLE
PRIMARY KEY BECOMES THE IDENTIFIATION OF THAT TABLE
YOU CANNOT JOIN A PRIMARY KEY WITH A PRIMARY KEY
YOU CANNOT HAVE DUPLICATE VALUES AND NULL VALUES IN PRIMARY KEY

-- FORIEGN KEY :
MAIN PURPOSE OF HAVING FORIEGN KEY IS TO ESTABLISH REFERNTIAL INTEGRITY.
REFERENTIAL INTEGRITY MEANS TO AVOID ORPHAN RECORDS INTO MY CHILD TABLE REFERENTIAL INTEGRITY HELP ME IN IDENTIFYING THESE RECORDS.
FOREIGN KEY IS THE REFERENTIAL INTEGRITY CHECK.
PRIMARY KEY IS A UNIQUE IDENTIFIER OF THE TABLE WHERE AS FOREIGN KEY IS THE REFERENTIAL INTEGRITY CHECK.
YOU CAN HAVE MULTIPLE FORIEGN KEYS.
*/
CREATE DATABASE DUP_DB;
USE DUP_DB;
CREATE TABLE CUSTOMER_TABLE
(
CID INT PRIMARY KEY,
CNAME VARCHAR(500)
);

INSERT INTO CUSTOMER_TABLE(CID,CNAME)
VALUES(1,'DV'),
(2,'BIGYAN'),
(3,'PANKRAJ'),
(4,'LINGRAJ');

SELECT * FROM CUSTOMER_TABLE;

INSERT INTO CUSTOMER_TABLE(CID,CNAME)
VALUES(5,'DV');

SELECT * FROM CUSTOMER_TABLE;

CREATE TABLE ADDRESS_TABLE
(
  AID INT PRIMARY KEY ,
  CITY VARCHAR(200),
  CID INT,
  FOREIGN KEY (CID) REFERENCES CUSTOMER_TABLE(CID)
);

SELECT * FROM ADDRESS_TABLE;

INSERT INTO ADDRESS_TABLE (AID,CITY,CID)
VALUES (1,'HYDERABAD',1) ;

SELECT * FROM ADDRESS_TABLE;

INSERT INTO ADDRESS_TABLE (AID,CITY,CID)
VALUES (45,'HYDERABAD',2) ;
INSERT INTO ADDRESS_TABLE (AID,CITY,CID)
VALUES (2,'HYDERABAD',3) ;







-- TO REMOVE FORIEGN KEY CONSTRAINT
ALTER TABLE ADDRESS_TABLE DROP FOREIGN KEY address_table_ibfk_1;



INSERT INTO ADDRESS_TABLE (AID,CITY,CID)
VALUES (101,'HYDERABAD',7) ;
INSERT INTO ADDRESS_TABLE (AID,CITY,CID)
VALUES (10,'DELHI',1) ;
-- JOINS
/*
 JOINS ARE USED TO CONNECT TWO OR MORE TABLES TOGETHER BASED ON A COMMON COLUMN.
 IN 99% OF THE CASES THE COMMON COLUMNS WILL HAVE SAME NAME 
CUSTOMER_TABLE -RIGHT           ADDRESS_TABLE - LEFT
CID|CNAME                        AID |   CITY   | CID
1  |DV                             1 | HYDERABAD| 1
2  |BIGYAN                         2 | HYDERABAD| 3
3  |PANKRAJ                       45 | HYDERABAD| 2
4  |LINGRAJ                      101 | HYDERABAD| 7
5  |DV                             


-- INNERJOIN
Retrieves only the matching rows from both tables based on the join condition.
Rows that do not have matching values in both tables are excluded from the result.
CID |CNAME   |AID | CITY    |  CID
1	|DV	     |1	  |HYDERABAD| 	1
3	|PANKRAJ |2	  |HYDERABAD| 	3
2	|BIGYAN	 |45  |HYDERABAD|	2


-- LEFT JOIN 
Retrieves all rows from the left table and matching rows from the right table.
If no match is found, NULL values are returned for columns from the right table.
CID |CNAME   | AID  |   CITY    |CID
1	|DV	     | 1	|HYDERABAD	|1
2	|BIGYAN  | 45	|HYDERABAD	|2
3	|PANKRAJ | 2	|HYDERABAD	|3
4	|LINGRAJ |NULL	| NULL      |NULL
5	|DV		 |NULL  | NULL      |NULL	
 
 
 -- RIGHT JOIN
Retrieves all rows from the right table and matching rows from the left table.
If no match is found, NULL values are returned for columns from the left table.
CID | CNAME  |  AID |  CITY    |CID
1	| DV	 | 1	|HYDERABAD |1
3	|PANKRAJ | 2	|HYDERABAD |3
2	|BIGYAN  | 45	|HYDERABAD |2
NULL|NULL	 | 101	|HYDERABAD |7
 
 
 CUSTOMER_TABLE -RIGHT           ADDRESS_TABLE - LEFT
CID|CNAME                        AID |   CITY   | CID
1  |DV                             1 | HYDERABAD| 1
2  |BIGYAN                         2 | HYDERABAD| 3
3  |PANKRAJ                       45 | HYDERABAD| 2
4  |LINGRAJ                      101 | HYDERABAD| 7
5  |DV                             10| DELHI    | 1
  
  -- INNER
1	DV  	1	HYDERABAD	1
3	PANKRAJ	2	HYDERABAD	3
1	DV	    10	DELHI	    1
2	BIGYAN	45	HYDERABAD	2


 -- LEFT
CID CNAME   AID   CITY       CID
1	DV  	 1	  HYDERABAD  1
1	DV	     10	  DELHI	     1
2	BIGYAN	 45	  HYDERABAD	 2
3	PANKRAJ	 2	  HYDERABAD	 3
4	LINGRAJ	 NULL NULL       NULL		
5	DV		 NULL NULL       NULL	
 
 -- RIGHT
CID  CNAME  AID  CITY       CID
1	 DV	     1	 HYDERABAD	1
3	 PANKRAJ 2	 HYDERABAD	3
1	 DV	     10	 DELHI	    1
2	 BIGYAN	 45	 HYDERABAD	2
NULL NULL	 101 HYDERABAD	7
 
 
 
 
 */
 SELECT * FROM CUSTOMER_TABLE;
 SELECT * FROM ADDRESS_TABLE;
 
 -- INNERJOIN
 SELECT * FROM CUSTOMER_TABLE
 INNER JOIN ADDRESS_TABLE 
 ON CUSTOMER_TABLE.CID=ADDRESS_TABLE.CID;
 -- LEFTJOIN
SELECT * FROM CUSTOMER_TABLE
LEFT JOIN ADDRESS_TABLE 
ON CUSTOMER_TABLE.CID=ADDRESS_TABLE.CID;
-- RIGHTJOIN
SELECT * FROM CUSTOMER_TABLE
RIGHT JOIN ADDRESS_TABLE 
ON CUSTOMER_TABLE.CID=ADDRESS_TABLE.CID;
 
SELECT CUSTOMER_TABLE.CNAME,ADDRESS_TABLE.CITY FROM CUSTOMER_TABLE
INNER JOIN ADDRESS_TABLE 
ON CUSTOMER_TABLE.CID=ADDRESS_TABLE.CID;
 
 /*
 A.ID               B.ID               CID
 1                    2                 1                                                                    
 2                    4                 5                                                 
 3                    5                 4                                               
 4                    6                 3                                               
 5                    9                 10                                                                                 
SELECT * FROM A    INNER JOIN B ON A.ID=B.ID  INNER JOIN C ON C.ID= B.ID
a.id|b.id|c.id|
4   |4   |4   |
5   |5   |5   |
SELECT * FROM A    LEFT JOIN B ON A.ID=B.ID  INNER JOIN C ON C.ID= B.ID
a.id|b.id|c.id|
4   |4   |4   |
5   |5   |5   |
SELECT * FROM A    LEFT JOIN B ON A.ID=B.ID  RIGHT JOIN C ON C.ID= B.ID
a.id|b.id|c.id|
1   |NULL|1   |
5   |5   |5   |
4   |4   |4   |
NULL|NULL|3   |
NULL|NULL|10  |
NULL|NULL|9   |
*/